name: Pull Request Build
on:
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: npm install
      - run: npm install --workspaces
      - run: npm run-script build -w=@uiw/react-baidu-map-api-loader
      - run: npm run-script build -w=@uiw/react-baidu-map
      - run: npm run-script build -w=@uiw/react-baidu-map-canvas-layer
      - run: npm run-script build -w=@uiw/react-baidu-map-circle
      - run: npm run-script build -w=@uiw/react-baidu-map-control
      - run: npm run-script build -w=@uiw/react-baidu-map-copyright-control
      - run: npm run-script build -w=@uiw/react-baidu-map-curve-line
      - run: npm run-script build -w=@uiw/react-baidu-map-custom-overlay
      - run: npm run-script build -w=@uiw/react-baidu-map-drawing-manager
      - run: npm run-script build -w=@uiw/react-baidu-map-geolocation-control
      - run: npm run-script build -w=@uiw/react-baidu-map-ground-overlay
      - run: npm run-script build -w=@uiw/react-baidu-map-info-window
      - run: npm run-script build -w=@uiw/react-baidu-map-label
      - run: npm run-script build -w=@uiw/react-baidu-map-map
      - run: npm run-script build -w=@uiw/react-baidu-map-marker
      - run: npm run-script build -w=@uiw/react-baidu-map-navigation-control
      - run: npm run-script build -w=@uiw/react-baidu-map-overview-map-control
      - run: npm run-script build -w=@uiw/react-baidu-map-panorama-control
      - run: npm run-script build -w=@uiw/react-baidu-map-point-collection
      - run: npm run-script build -w=@uiw/react-baidu-map-polygon
      - run: npm run-script build -w=@uiw/react-baidu-map-polyline
      - run: npm run-script build -w=@uiw/react-baidu-map-require-script
      - run: npm run-script build -w=@uiw/react-baidu-map-scale-control
      - run: npm run-script build -w=@uiw/react-baidu-map-tile-layer
      - run: npm run-script build -w=@uiw/react-baidu-map-type-control
      - run: npm run-script build -w=@uiw/react-baidu-map-types
      - run: npm run-script build -w=@uiw/react-baidu-map-utils
      - run: npm run-script build -w=@uiw/react-baidu-map-with-map
      - run: npm run coverage
      - run: npm run doc
      - run: npm ls @babel/core