name: Pull Request Build
on:
  pull_request:

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: npm -v
      - run: npm install -g npm@7
      - run: npm -v
      - run: npm install
      - run: npm install --workspaces
      - run: npm run build
      - run: npm run doc
      - run: npm run coverage